### ISSUE TITLE
Error building Collection 1.6.2 on XCode 6.4

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [BadChoice/Collection#1]
Hi,

when I try to compile my project with Collection installed by pod, I get the following errors

`Parse Issue Group
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:40:60: Expected ')'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:47:69: Expected ')'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:55:69: Expected ')'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:15:97: Expected ')'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:21:97: Expected ')'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:27:74: Expected ')'
Semantic Issue Group
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:41:19: Use of undeclared identifier 'key'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:41:24: Use of undeclared identifier 'obj'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:40:45: Incompatible block pointer types sending 'void (^)(__strong id)' to parameter of type 'void (^)(__strong id, __strong id, BOOL *)'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:48:26: Use of undeclared identifier 'key'; did you mean 'keys'?
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:48:30: Use of undeclared identifier 'obj'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:47:50: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, __strong id, BOOL *)'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:56:28: Use of undeclared identifier 'key'; did you mean 'keys'?
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:56:28: Reference to local variable 'keys' declared in enclosing context
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:56:32: Use of undeclared identifier 'obj'
/.../Pods/Collection/Collection/Categories/NSDictionary+Collection/NSDictionary+Collection.m:55:50: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, __strong id, BOOL *)'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:16:26: Use of undeclared identifier 'evaluatedObject'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:15:78: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, NSDictionary *__strong)'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:22:27: Use of undeclared identifier 'evaluatedObject'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:21:78: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, NSDictionary *__strong)'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:28:26: Use of undeclared identifier 'obj'
/.../Pods/Collection/Collection/Categories/NSArray+Collection/NSArray+Collection.m:27:55: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, NSUInteger, BOOL *)'`

Can you help me please? I need the application on iOS 7.0

P.S.: If i try to compile the same project with the latest XCode, it successfully compile my project.

Thanks

**Comment by BadChoice** [comment]
are you using swift?
Can you share the project with me so I can check, I have no idea why it fails hehe

**Comment by Bruno-Piccinin-RealComm** [comment]
Nope, objective-c. 
Yep I can share the project with you
Even if you try to 

1. create a new sample project
2. create pod file by pod init
3. add pod 'Collection' in pod file
4. run pod install
5. open sampleproject.workspace
6. build project

[sampleproject.zip](https://github.com/BadChoice/Collection/files/868629/sampleproject.zip)

**Comment by BadChoice** [comment]
Your project compiled to me

I'm using cocoa pods versión : `1.2.0.beta.1`

And you need to run the `sampleproject.xcworkspace` project, not the `sampleproject.xcodeproj`

I'm also using xcode 8.2.1 (8C1002) if it helps

**Comment by Bruno-Piccinin-RealComm** [comment]
I'm using `cocoapods-1.1.1`.

I'm already using `sampleproject.xcworkspace` project and NOT the `sampleproject.xcodeproj`

With `XCode 8.2.1 (8C1002)` it works perfectly, but since I have to test the app on iOS 7.0 Simulator and I can't try it on XCode 8.2.1. So I'm trying to use `XCode 6.4 (6E35b)` and on THIS version of XCode i have the errors posted on previous comment.

You can try by yourself to install `XCode 6.4 (6E35b)` and try to install the sample project I sent you. You will probably get my errors too. 

Is the Collection pod maybe not compatible on `XCode 6.4 (6E35b)` version? 
Have I maybe try to use older version of cocoapods or older version of Collection pod?
There is any other way to test my app on Simulator with iOS 7.0 with `XCode 8.2.1 (8C1002)`?

**Comment by BadChoice** [comment]
Ok I understand, 
I never tried in xcode 6, but collections should works there, actually, you download the collections project https://github.com/BadChoice/Collection.git and try to compile it alone, if it works, then you can try to copy the `categories` folder in your poject and see if it works too

Let me know if that worked, so we can then try to find a solution

**Comment by Bruno-Piccinin-RealComm** [comment]
Ok,
I tried to clone project [https://github.com/BadChoice/Collection.git](https://github.com/BadChoice/Collection.git) and I tried to compile it with `XCode 8.2.1 (8C1002)`. 
By the way it seems no `pod install` required, so I used `Collection.xcodeproj`.
With `XCode 8.2.1 (8C1002)` everithing works fine.

I tried the same exact thing on `XCode 6.4 (6E35b)` and I got basicly the exact same errors a had on sample project sent to you.

```
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:15:97: Expected ')'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:16:26: Use of undeclared identifier 'evaluatedObject'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:15:78: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, NSDictionary *__strong)'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:21:97: Expected ')'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:22:27: Use of undeclared identifier 'evaluatedObject'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:21:78: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, NSDictionary *__strong)'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:27:74: Expected ')'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:28:26: Use of undeclared identifier 'obj'
/…/BadChoice-Collection-iOS-master/Collection/Categories/NSArray+Collection/NSArray+Collection.m:27:55: Incompatible block pointer types sending 'BOOL (^)(__strong id)' to parameter of type 'BOOL (^)(__strong id, NSUInteger, BOOL *)'
```
Among other, the files that generate errors are in the `categories` folder as you can se from the errors above, the same folder I should use in my project.

Any ideas?

P.S.: It seems like XCode cant recognize the code after `predicateWithBlock:`
```
[NSPredicate predicateWithBlock:^BOOL(id  _Nonnull evaluatedObject, NSDictionary<NSString *,id> * _Nullable bindings) {
        return condition(evaluatedObject);
    }]];

```

**Comment by BadChoice** [comment]
I believe it was added in further versions, that's why it is not working..
I'm afraid I don't have that 6.4 verions to try to find an alternative solution, :(

**Comment by BlackImpermanent** [comment]
Wow! It's a pity that I'm a Java programmer

**Comment by BadChoice** [comment]
Could you update your xcode version and make it work?

**Comment by BadChoice** [comment]
Closing it due to inactivity
